### ISSUE TITLE
Docker : "not found"

### ISSUE THREAD

**Issue by Draky50110** [easymesh/autoproxy-web#1]
Hello.

Tried your command and when accessing IP:8000, it gives a blank page with "Not found" only.

Any idea ?

Log : 

GoAdmin 启动成功。
目前处于 "debug" 模式。请在生产环境中切换为 "release" 模式。
2023-02-10T16:42:04.120Z	INFO	engine/engine.go:402	=====> 初始化数据库连接
2023-02-10T16:42:04.131Z	INFO	engine/engine.go:402	=====> 初始化配置
`sqlite` is not officially supported, running under compatibility mode.
2023/02/10 16:42:04.139 [I]  http server Running on http://0.0.0.0:8000

**Comment by linimbus** [comment]
You can try access this curl `http://{ip}:8000/admin/login`
